---
title: "RIPoL Tree-aware Enrichment Analysis"
author: "Your Name"
output: html_document
---

## 1. Load Required Libraries

```{r setup, message=FALSE, warning=FALSE}
library(phyloseq)
library(dplyr)
library(ggplot2)
library(patchwork)

# Load custom functions
source("Functions.R")

# Load phyloseq object
load("tumor_rooted.RData")
```

## 2. Prepare Phyloseq Object

```{r}
# Extract rooted phyloseq object
ps <- physeq.tree

# Remove control samples
ps <- subset_samples(ps, group != "C")

# Convert sample metadata to data frame
sd <- as.data.frame(sample_data(ps))

# Split group variable into prefix (diagnosis) and suffix (confounder)
sd$group_prefix <- substr(as.character(sd$group), 1, 3)
sd$group_suffix <- substr(
  as.character(sd$group),
  nchar(as.character(sd$group)),
  nchar(as.character(sd$group))
)

# Assign modified metadata back to phyloseq object
sample_data(ps) <- sample_data(sd)

# Remove taxa with zero total counts
ps <- prune_taxa(taxa_sums(ps) > 0, ps)
```


## 3. Temperature Selection via BTS

```{r}
# Estimate smoothing parameter tau using BTS procedure
tau_lib <- BTS(ps)
```

## 4. Tree-aware Label Propagation

### 4.1 Weighted Propagation

```{r}
Rtree_weighted <- RIPoL_tree(
  ps,
  outcome_var = "group_prefix",
  confounder_vars = "group_suffix",
  tau = 0.0171,
  weighted = TRUE
)
```

### 4.2 Unweighted Propagation

```{r}
Rtree_unweighted <- RIPoL_tree(
  ps,
  outcome_var = "group_prefix",
  confounder_vars = "group_suffix",
  tau = 0.0171,
  weighted = FALSE
)
```

## 5. Core Taxa Identification

```{r}
core_res <- generate_core_taxa(
  Rtree_weighted,
  Rtree_unweighted,
  gamma_weighted = 0.01,
  gamma_unweighted = 0.01,
  physeq = ps
)

# Extract LTS core taxa and genera
core_genera_LTS <- core_res$core_taxa_by_class[["LTS"]]
genus_LTS <- unique(core_res$taxonomy_table[core_genera_LTS, "Genus"])

# Extract STS core taxa and genera
core_genera_STS <- core_res$core_taxa_by_class[["STS"]]
genus_STS <- unique(core_res$taxonomy_table[core_genera_STS, "Genus"])
```

## 6. Enrichment vs Prevalence Analysis (LTS)

```{r}
enrich_res <- compute_enrichment_vs_prevalence2(
  ps,
  Rtree_weighted,
  Rtree_unweighted,
  "group_prefix",
  "LTS"
)
```

## 7. Visualization

### 7.1 Individual Plots

```{r}
enrich_res$plot1
enrich_res$plot2
enrich_res$plot3
enrich_res$plot4
```

### 7.2 Scatter Diagnostics

```{r}
plot(
  enrich_res$table$Unweighted_z ~ enrich_res$table$Prevalence,
  xlab = "Prevalence",
  ylab = "Unweighted Z-score"
)

plot(
  enrich_res$table$Weighted_z ~ enrich_res$table$Mean_abundance,
  xlab = "Mean Abundance",
  ylab = "Weighted Z-score"
)
```

### 7.3 Two-Panel Figure with Labels  (fig 2 AB)

```{r}
final_plot_ab_labeled <- wrap_plots(
  enrich_res$plot1,
  enrich_res$plot4,
  ncol = 2
) + plot_annotation(tag_levels = 'A')


final_plot_ab_labeled

```